### DISCUSSION TITLE
How to upload dcm file to DCM4CHEE using RESTFUL API?

### DISCUSSION THREAD

**Discussion by oliverfchen** [dcm4che/dcm4chee-arc-light#3375] [Q&A] [answered]
Is there a function in RESTFUL API that can do the same thing as storescu in pynetdicom? Request sample, please.
follow this link: https://github.com/dcm4che/dcm4chee-arc-light/issues/194
and: https://www.leadtools.com/help/sdk/v20/dh/to/leadtools-dicomweb-stow-rs.html
not successful.

**Comment by gunterze** [comment, marked as answer]
dcm4chee-arc supports [DICOM PS.3.18 Store Transaction](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.5) by HTTP [`POST /dcm4chee-arc/aets/{aet}/rs/studies`](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STOW-RS/StoreInstances)

Wiki: [Store objects by STOW RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Store-objects-by-STOW-RS)

**Reply by oliverfchen** [reply]
Hi, thanks for your reply, but I still can't get it to work. Could you give me an example command of how to POST the file in the command line?
curl -H "Content-Type: multipart/related; type=\"application/dicom\"" -F "content=@after.dcm; type=application/dicom" -X POST http://121.37.162.242:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies  -i -v 
it did not work.

**Reply by oliverfchen** [reply]
I used curl command but got "internal server error":
C:\Users\12755575\Desktop\Medical_image\Python_Code\dcm\sample_dcm>curl -X POST -H "Content-Type: multipart/related; type=\"application/dicom\"; boundary=myboundary" http://192.168.8.157:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies --data-binary @dicom.mime -i -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.8.157:8080...
* Connected to 192.168.8.157 (192.168.8.157) port 8080 (#0)
> POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies HTTP/1.1
> Host: 192.168.8.157:8080
> User-Agent: curl/7.71.1
> Accept: */*
> Content-Type: multipart/related; type="application/dicom"; boundary=myboundary
> Content-Length: 527433
>
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Connection: keep-alive
Connection: keep-alive
< Content-Type: text/html;charset=UTF-8
Content-Type: text/html;charset=UTF-8
< Content-Length: 80
Content-Length: 80
< Date: Wed, 22 Sep 2021 14:50:39 GMT
Date: Wed, 22 Sep 2021 14:50:39 GMT

<
<html><head><title>Error</title></head><body>Internal Server Error</body></html>* Connection #0 to host 192.168.8.157 left intact

**Reply by nuttycat** [reply]
I have the same problem when I use the ui2 web page to upload a dicom file.
There is an error in wildfly logs.
```
2021-09-29 14:29:25,632 WARN  [org.dcm4chee.arc.stow.StowRS] (default task-6) Failed to process Part #1{content-disposition=[form-data;name="file";filename="1.2.26.3680043.2.428.4.20140411090343.745526.0906374841.dcm"], content-type=[application/dicom]}
2021-09-29 14:29:25,633 WARN  [org.dcm4chee.arc.stow.StowRS] (default task-6) Response Internal Server Error caused by java.lang.NullPointerException
	at deployment.dcm4chee-arc-ear-5.24.1-psql.ear.dcm4chee-arc-store-5.24.1.jar//org.dcm4chee.arc.store.impl.StoreContextImpl.getSopClassUID(StoreContextImpl.java:103)
	at deployment.dcm4chee-arc-ear-5.24.1-psql.ear.dcm4chee-arc-war-5.24.1-unsecure.war//org.dcm4chee.arc.stow.StowRS.storeDicomObject(StowRS.java:468)
......
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

My docker compose file:
```
version: "3.8"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.57-24.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    deploy:
      placement:
        constraints:
          - 'node.labels.nm == dev1'
    volumes:
      - /home/ubuntu/dcm4chee-swarm/v/ldap:/var/lib/openldap/openldap-data
      - /home/ubuntu/dcm4chee-swarm/v/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:13.3-24
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    deploy:
      placement:
        constraints:
          - 'node.labels.nm == dev1'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/ubuntu/dcm4chee-swarm/v/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.24.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8081:8080"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    deploy:
      placement:
        constraints:
          - 'node.labels.nm == dev1'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/ubuntu/dcm4chee-swarm/v/wildfly:/opt/wildfly/standalone
      - /home/ubuntu/dcm4chee-swarm/v/storage:/storage
```
