### DISCUSSION TITLE
Installation with Docker Swarm as per wiki failing

### DISCUSSION THREAD

**Discussion by neurorepro** [dcm4che/dcm4chee-arc-light#3771] [General]
**Describe the bug**
I am trying to setup dcm4chee with Docker Swarm as per the wiki [here](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-using-Docker-Swarm), but the first verification at URL `https://<arc-node>:8843/admin/dcm4che/console` failed (blank webpage). 

**To Reproduce**
1. Have a host server
2. Create 3 VMs (nodes) with docker installed. Name them `d4c-archive`, `d4c-db` and `d4c-logs` for the archive, database and elastic nodes respectively.
3. Check that within each node, you can ping the others from their hostnames (e.g. when in `d4c-archive`, `ping d4c-logs` works) 
4. Follow the exact instructions of the [wiki](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-using-Docker-Swarm), using the hostnames above. 
5. Run `docker stack deploy -c docker-compose.yml dcm4chee`
6. Get the IP of the node `d4c-archive`, say W.X.Y.Z
7. See blank page when trying to get `https://W.X.Y.Z:8843/admin/dcm4che/console` (although `https://W.X.Y.Z:8843 show keycloak page`) whatever the browser (Chrome, Firefox, Chrome incognito window, ...)

**Additional context**
I'm not sure the Docker Stack file (i.e. `docker-compose.yml`) shown in the wiki was tested because there was an error in it which prevented it to work properly (`mode: host` was required by the `oauth2-proxy` service to run, and this was missing in the stack file in the wiki). The one i used was:

<details>
 <summary> docker-compose.yml file used with Docker Stack (click arrow to see)

PS: I was not sure if `KEYCLOAK_WAIT_FOR: db:389 logstash:8514` should be `KEYCLOAK_WAIT_FOR: d4c-db:389 d4c-logs:8514`, and `WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514` should be `WILDFLY_WAIT_FOR: d4c-db:389 d4c-db:5432 logstash:8514`, or if it doesn't matter since the docker internal DNS refer to the same IP as the host node's in a 1-replica swarm configuration.

</summary>

```yaml
version: "3.5"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      discovery.type: single-node
      xpack.security.enabled: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/esdatadir:/usr/share/elasticsearch/data
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-logs]
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-logs]
  logstash:
    image: dcm4che/logstash-dcm4chee:8.3.2-14
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - target: 12201
        published: 12201
        protocol: udp
        mode: host
      - target: 8514
        published: 8514
        protocol: udp
        mode: host
      - target: 8514
        published: 8514
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/logstash/filter-hashtree:/usr/share/logstash/data/filter-hashtree
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-logs]
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.2-27.0
    logging:
      driver: gelf
      options:
        gelf-address: "udp://d4c-logs:12201"
        tag: ldap
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-db]
  keycloak:
    image: dcm4che/keycloak:18.0.1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://d4c-logs:12201"
        tag: keycloak
    ports:
      - target: 8843
        published: 8843
        protocol: tcp
        mode: host
    env_file: docker-compose.env
    environment:
      KC_HTTPS_PORT: 8843
      KC_HOSTNAME: d4c-archive
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: supersecretkeycloak
      KC_LOG: file
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI: "true"
      GELF_ENABLED: "true"
      LOGSTASH_HOST: d4c-logs
      KIBANA_CLIENT_ID: kibana
      KIBANA_CLIENT_SECRET: supersecretkibana
      KIBANA_REDIRECT_URL: "https://d4c-archive:8643"
      KEYCLOAK_WAIT_FOR: db:389 logstash:8514
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/data
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-archive]
  oauth2-proxy:
    image: dcm4che/oauth2-proxy:7.3.0
    ports:
      - target: 8643
        published: 8643
        protocol: tcp
        mode: host
    environment:
      OAUTH2_PROXY_HTTPS_ADDRESS: 0.0.0.0:8643
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_UPSTREAMS: "http://kibana:5601"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://d4c-archive:8843/realms/dcm4che"
      OAUTH2_PROXY_REDIRECT_URL: "https://d4c-archive:8643/oauth2/callback"
      OAUTH2_PROXY_ALLOWED_ROLE: auditlog
      OAUTH2_PROXY_CLIENT_ID: kibana
      OAUTH2_PROXY_CLIENT_SECRET: supersecretkibana
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: "sub"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      OAUTH2_PROXY_COOKIE_SECRET: T0F1dGhLaWJhbmFUZXN0cw==
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_TLS_CERT_FILE: /etc/certs/cert.pem
      OAUTH2_PROXY_TLS_KEY_FILE: /etc/certs/key.pem
      OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR: /templates
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-archive]
  db:
    image: dcm4che/postgres-dcm4chee:14.4-27
    logging:
      driver: gelf
      options:
        gelf-address: "udp://d4c-logs:12201"
        tag: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-db]
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.27.0-secure
    logging:
      driver: gelf
      options:
        gelf-address: "udp://d4c-logs:12201"
        tag: dcm4chee-arc
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 9990
        published: 9990
        protocol: tcp
        mode: host
      - target: 9993
        published: 9993
        protocol: tcp
        mode: host
      - target: 11112
        published: 11112
        protocol: tcp
        mode: host
      - target: 2762
        published: 2762
        protocol: tcp
        mode: host
      - target: 2575
        published: 2575
        protocol: tcp
        mode: host
      - target: 12575
        published: 12575
        protocol: tcp
        mode: host
    env_file: docker-compose.env
    environment:
      LOGSTASH_HOST: d4c-logs
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname == d4c-archive]
```
</details>

<details>
 <summary>docker-compose.env file used</summary>

```console
LOGSTASH_HOST=d4c-logs
SYSLOG_HOST=d4c-logs
SYSLOG_PORT=8514
SYSLOG_PROTOCOL=TLS
STORAGE_DIR=/storage/fs1
POSTGRES_DB=pacsdb
POSTGRES_USER=pacs
POSTGRES_PASSWORD=pacs
AUTH_SERVER_URL=https://d4c-archive:8843
ARCHIVE_HOST=d4c-archive
```
</details>
