### DISCUSSION TITLE
Request to change the port

### DISCUSSION THREAD

**Discussion by AstridTrj** [dcm4che/dcm4chee-arc-light#3804] [Q&A]
I have a need to change the port. The original configuration is as follows:
```
version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /data_warehouse/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /data_warehouse/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:12.2-22
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data_warehouse/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.22.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data_warehouse/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /data_warehouse/dcm4chee-arc/storage:/storage
```

Due to port conflicts，I want to change all the ports, include 389 and 5432.  Configured as below：
```
version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "489:389"
    env_file: docker-compose.env
    volumes:
      - /data_warehouse/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /data_warehouse/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:12.2-22
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "6432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data_warehouse/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.22.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "9080:8080"
      - "9443:8443"
      - "10990:9990"
      - "10993:9993"
      - "12112:11112"
      - "3762:2762"
      - "3575:2575"
      - "13575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:489 db:6432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data_warehouse/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /data_warehouse/dcm4chee-arc/storage:/storage
```
Although three dockers of dcm4chee are started, i can't access http://xxxx:9080/dcm4chee-arc/ui2. The error while accessing is "unable to establish a connection to the server". Then I revert "WILDFLY_WAIT_FOR: ldap:489 db:6432" to "WILDFLY_WAIT_FOR: ldap:389 db:5432" and start again. Finally, i can access  http://xxxx:9080/dcm4chee-arc/ui2, but the page has nothing and an error occurred when i click the "Navigation" on the left menu.
![image](https://user-images.githubusercontent.com/40670592/192779964-7ea43f66-85c0-4985-a954-dc9176c212d3.png)

I would like to know if all ports can be modified. I would be very grateful if anyone could help me.
