### DISCUSSION TITLE
I want to use oss/minio as a online storage.replace fs1

### DISCUSSION THREAD

**Discussion by lxb0425** [dcm4che/dcm4chee-arc-light#3961] [General]
I replace storage URI 
![image](https://user-images.githubusercontent.com/50564015/219539799-33628006-6a07-435d-ac0b-1e40b3d62e37.png)

but it is wrong
![image](https://user-images.githubusercontent.com/50564015/219539945-eb2020fd-1669-4876-a882-5db6e24c8745.png)

**Comment by lxb0425** [comment]
version 5.28.0

**Comment by vrindanayak** [comment]
@lxb0425 : Verify if you have also correctly set the Storage Properties of your [S3-Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/S3-Storage)

**Reply by lxb0425** [reply]
storage uri use emc-ecs-s3 or jclouds:s3 ? 
my storage only minio , not Amazon S3.

**Comment by hadn11** [comment]
I want to use oss/minio too and this config work for me:

```
# Storage URI
jclouds:aws-s3:http://minio:9000/dcm4che

# Storage Property:
container=dcm4che
jclouds.s3.virtual-host-buckets=true
credential=changeit
identity=changeit
jclouds.strip-expect-header=true
containerExists=true
jclouds.relax-hostname=true
jclouds.trust-all-certs=true
```

Docker compose for minio:
```
  dcm4che.minio: # need to change name to format <bucket-name>.minio
    image: 'docker.io/bitnami/minio:2022.8.8-debian-11-r0'
    volumes:
        - ./data_minio:/data
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        MINIO_ROOT_USER: 'changeit'
        MINIO_ROOT_PASSWORD: 'changeit'
    logging:
        driver: json-file
        options:
          max-size: "10m"
```
