### ISSUE TITLE
Running with Docker ldap broken connection

### ISSUE THREAD

**Issue by jimOnAir** [dcm4che/dcm4chee-arc-light#1468]
Hi. I'm trying to run dcm4chee with Docker and have a problem with ldap connection. After some time (about 15-20 minutes) of innactivity first api or web-ui query return 500 error  
  
`"javax.naming.ServiceUnavailableException: ldap:389; socket closed; remaining name 'cn=Devices,cn="Dicom Configuration",dc=mdw,dc=io'`  
  
I see this error in server.log: 
`2018-06-22 08:40:28,931 INFO  [org.dcm4che3.conf.ldap.ReconnectDirContext] (default task-1) Connection to ldap://ldap:389 broken - reconnect`
Next query seems to pass normal.  
  
My docker-compose file:
```
version: '3.6'
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-13.1
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: ldap
        target: /var/lib/ldap
      - type: volume
        source: slapd.d
        target: /etc/ldap/slapd.d
    networks:
      - mdw
    deploy:
      placement:
        constraints:
          - node.labels.dcm4chee == true
  dcm4che-postgres:
    image: dcm4che/postgres-dcm4chee:10.0-13
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:      
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - type: volume
      source: db
      target: /var/lib/postgresql/data
    networks:
      - mdw
    deploy:
      placement:
        constraints:
          - node.labels.dcm4chee == true
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.13.1
    ports:
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 dcm4che-postgres:5432
      POSTGRES_HOST: dcm4che-postgres
      LDAP_HOST: ldap
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs="org.jboss.byteman" -Djava.awt.headless=true -Dcom.sun.jndi.ldap.connect.pool=true -Dcom.sun.jndi.ldap.connect.pool.maxsize=30 -Dcom.sun.jndi.ldap.connect.pool.prefsize=10 -Dcom.sun.jndi.ldap.connect.pool.timeout=60000
    depends_on:
      - ldap
      - dcm4che-postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: wildfly
        target: /opt/wildfly/standalone
      - type: volume
        source: storage
        target: /storage
    networks:
      - mdw
      - reverse-proxy
    deploy:
      placement:
        constraints:
          - node.labels.dcm4chee == true

networks:
  mdw:
    external: true
  reverse-proxy:
    external: true
volumes:
  ldap:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-ldap-{{.Task.Slot}}'
  slapd.d:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-slapd.d-{{.Task.Slot}}'
  db:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-db-{{.Task.Slot}}'
  keycloak:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-keycloak-{{.Task.Slot}}'
  wildfly:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-wildfly-{{.Task.Slot}}'
  storage:
    external: true
    name: '{{index .Service.Labels "com.docker.stack.namespace"}}-storage-{{.Task.Slot}}'
```
I'm running Docker 18.05.0-ce, build f150324 in swarm mode on ubunut 16.04 in Amazon AWS cloud
