### ISSUE TITLE
Avoid update of $JAVA_HOME/lib/security/cacerts if $TRUSTSTORE=$JAVA_HOME/lib/security/cacerts by archive and keycloak docker images 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2741]
_Rationale:_
If the archive/keycloak is configured to trust all JDK Root CA Certificates by 
```yaml
    environment:
      TRUSTSTORE: /usr/local/openjdk-11/lib/security/cacerts
      TRUSTSTORE_PASSWORD: changeit
``` 
there is no need import the certificates specified referred by` $TRUSTSTORE` to `$JAVA_HOME/lib/security/cacert`s
