### ISSUE TITLE
archive docker image: Login into Wildfly Management Console fails if AUTH_SERVER_URL=https://keycloak:<port>

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3805]
Login into Wildfly Management Console fails, if AUTH_SERVER_URL is configured to connect over the overlay network to keycloak, instead (also) connect via the Frontend Endpoint URL of the Keycloak server. E.g.:
```yaml
    environment:
      AUTH_SERVER_URL: https://keycloak:8843
      UI_AUTH_SERVER_URL: https://gunter-nb:8843
```
Fix:
```
             <secure-server name="wildfly-console">
                 <realm>${env.REALM_NAME:dcm4che}</realm>
-                <auth-server-url>${env.AUTH_SERVER_URL:https://keycloak:8443}</auth-server-url>
+                <auth-server-url>${env.UI_AUTH_SERVER_URL:${env.AUTH_SERVER_URL:https://keycloak:8443}}</auth-server-url>
                 <public-client>true</public-client>
                 <ssl-required>${env.SSL_REQUIRED:external}</ssl-required>
                 <resource>${env.WILDFLY_CONSOLE:wildfly-console}</resource>
```
