### ISSUE TITLE
Use of LetsEncrypt Certificates fails without useful error

### ISSUE THREAD

**Issue by CPBridge** [dcm4che/dcm4chee-arc-light#3945]
**Describe the bug**

I am trying to setup a secured archive using a very similar docker compose setup to the one here: https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-on-a-single-host#use-docker-compose

This is working fine when I do not specify which certificates to use, meaning that the default certificates self-signed certificates built into the containers are used. However I want to use my own certificates, which I obtained from the letsencrypt certbot in `.pem` format, including `fullchain.pem`, `privkey.pem`, `cert.pem`, `chain.pem`.

Following advice on numerous other forums, I converted this to a `.p12` file using OpenSSL:

```
openssl pkcs12 -export \
    -in /etc/letsencrypt/live/my.domain/fullchain.pem \
    -inkey /etc/letsencrypt/live/my.domain/privkey.pem \
    -certfile /etc/letsencrypt/live/my.domain/chain.pem \
    -out /etc/letsencrypt/live/my.domain/cert.p12
``` 

This prompts me to add in a password to protect the file, say `p@ssword`.

However, when I then try to use this inside the docker compose set up as the certificate file for the archive container and/or the keycloak container, those two containers just die shortly after startup without any useful error message. Here is the compose file:

```yaml
version: "3"

services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.3-29.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    volumes:
      - /media/slim-data/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /media/slim-data/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:19.0.3
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8843:8843"
    env_file: docker-compose.env
    environment:
      KC_HTTPS_PORT: 8843
      KC_HOSTNAME: my.domain
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI: "true"
      KC_HTTPS_KEY_STORE_FILE: /etc/certs/cert.p12  # comment this line and it works
      KC_HTTPS_KEY_STORE_PASSWORD: "p@ssword"  # comment this line and it works
      KEYCLOAK_WAIT_FOR: ldap:389
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/letsencrypt/live/my.domain/:/etc/certs:ro
      - /media/slim-data/dcm4chee-arc/keycloak:/opt/keycloak/data
  db:
    image: dcm4che/postgres-dcm4chee:14.5-29
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/slim-data/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.29.0-secure
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      KEYSTORE: /etc/certs/cert.p12  # comment this line and it works
      KEYSTORE_PASSWORD: "p@ssword"  # comment this line and it works
    depends_on:
      - ldap
      - keycloak
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/letsencrypt/live/my.domain/:/etc/certs:ro
      - /media/slim-data/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /media/slim-data/dcm4chee-arc/storage:/storage
```

The docker compose output (after `docker-compose up`) looks like this:

```Creating network "compose_default" with the default driver
Creating compose_ldap_1 ... done
Creating compose_db_1       ... done
Creating compose_keycloak_1 ... done
Creating compose_arc_1      ... done
Attaching to compose_ldap_1, compose_db_1, compose_keycloak_1, compose_arc_1
db_1        |
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        |
db_1        | 2023-01-31 23:34:03.762 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1        | 2023-01-31 23:34:03.762 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2023-01-31 23:34:03.762 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2023-01-31 23:34:03.767 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2023-01-31 23:34:03.794 UTC [26] LOG:  database system was shut down at 2023-01-31 03:47:27 UTC
db_1        | 2023-01-31 23:34:03.880 UTC [1] LOG:  database system is ready to accept connections
ldap_1      | 63d9a56b.07d8ec5a 0x7fb66a12db48 @(#) $OpenLDAP: slapd 2.6.3 (Sep 17 2022 15:03:29) $
ldap_1      |   openldap
ldap_1      | 63d9a56b.19f218a4 0x7fb66a12db48 slapd starting
keycloak_1  | '/docker-entrypoint.d/themes/keycloak' -> '/opt/keycloak/themes/keycloak'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login' -> '/opt/keycloak/themes/keycloak/login'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources' -> '/opt/keycloak/themes/keycloak/login/resources'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/css' -> '/opt/keycloak/themes/keycloak/login/resources/css'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/css/login.css' -> '/opt/keycloak/themes/keycloak/login/resources/css/login.css'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/img' -> '/opt/keycloak/themes/keycloak/login/resources/img'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/img/bg2.jpg' -> '/opt/keycloak/themes/keycloak/login/resources/img/bg2.jpg'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/img/favicon.ico' -> '/opt/keycloak/themes/keycloak/login/resources/img/favicon.ico'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/resources/img/logo.png' -> '/opt/keycloak/themes/keycloak/login/resources/img/logo.png'
keycloak_1  | '/docker-entrypoint.d/themes/keycloak/login/theme.properties' -> '/opt/keycloak/themes/keycloak/login/theme.properties'
keycloak_1  | Importing keystore /opt/keycloak/conf/keystores/cacerts.p12 to /opt/java/openjdk/lib/security/cacerts...
arc_1       | Importing keystore /opt/wildfly/standalone/configuration/keystores/cacerts.p12 to /opt/java/openjdk/lib/security/cacerts...
keycloak_1  | Entry for alias mykey successfully imported.
keycloak_1  | Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
arc_1       | Entry for alias mykey successfully imported.
arc_1       | Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
keycloak_1  | Waiting for ldap:389 ...
keycloak_1  | done
keycloak_1  | Starting Keycloak 19.0.3
arc_1       | Waiting for ldap:389 ...
arc_1       | done
arc_1       | Waiting for db:5432 ...
arc_1       | done
arc_1       | Starting Wildfly 26.1.2.Final
arc_1       | =========================================================================
arc_1       |
arc_1       |   JBoss Bootstrap Environment
arc_1       |
arc_1       |   JBOSS_HOME: /opt/wildfly
arc_1       |
arc_1       |   JAVA: /opt/java/openjdk/bin/java
arc_1       |
arc_1       |   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.url.ldap=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.url.ldaps=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
arc_1       |
arc_1       | =========================================================================
arc_1       |
keycloak_1  | Changes detected in configuration. Updating the server image.
keycloak_1  | Updating the configuration and installing your custom providers, if any. Please wait.
arc_1       | WARNING: An illegal reflective access operation has occurred
arc_1       | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/wildfly/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-18.1.2.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
arc_1       | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
arc_1       | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
arc_1       | WARNING: All illegal access operations will be denied in a future release
compose_arc_1 exited with code 1
keycloak_1  | Server configuration updated and persisted. Run the following command to review the configuration:
keycloak_1  |
keycloak_1  |   kc.sh show-config
keycloak_1  |
keycloak_1  | Next time you run the server, just run:
keycloak_1  |
keycloak_1  |   kc.sh start --optimized
keycloak_1  |
compose_keycloak_1 exited with code 1
```

You'll see that the archive container and the keycloak container just die shortly after startup. The various warnings happen even if the default certs are used (when everything works fine), so I assume that they are likely unrelated.

Checking the keycloak log I did see this:
```
2023-01-31 23:34:42,938 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-01-31 23:34:42,938 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: /etc/certs/cert.p12
```

which is not very informative, and nothing else that seems to tell me what the issue is.

I know that this is likely just a problem with my certs and the conversion, but since I imagine many others may want to do similar things, I thought it would be worth posting here to see if anyone has any suggestions.

Thanks in advance for any help, and for a great project!

*OS Details*

- Ubuntu jammy 22.04
- Docker compose version: 1.29.2
- Docker version 20.10.12
